export const bench = [
  { position: "", name: "" },
  { position: "", name: "" },
  { position: "", name: "" },
  { position: "", name: "" },
  { position: "", name: "" },
  { position: "", name: "" },
  { position: "", name: "" },
  { position: "", name: "" },
  { position: "", name: "" },
  { position: "", name: "" },
  { position: "", name: "" },
  { position: "", name: "" },
  { position: "", name: "" },
  { position: "", name: "" },
  { position: "", name: "" },
];
