import { imagesFormations } from "../assets/img/formations/imagesFormations";

export const formations = [
  {
    title: "3412",
    image: imagesFormations["3-4-1-2"],
    positions: ["G", "D", "D", "D", "M", "M", "M", "M", "M", "F", "F"],
    selections: [
      { position: "G", name: "" },
      { position: "D", name: "" },
      { position: "D", name: "" },
      { position: "D", name: "" },
      { position: "M", name: "" },
      { position: "M", name: "" },
      { position: "M", name: "" },
      { position: "M", name: "" },
      { position: "M", name: "" },
      { position: "F", name: "" },
      { position: "F", name: "" },
    ],
  },
  {
    title: "343",
    image: imagesFormations["3-4-3"],
    positions: ["G", "D", "D", "D", "M", "M", "M", "M", "F", "F", "F"],
    selections: [
      { position: "G", name: "" },
      { position: "D", name: "" },
      { position: "D", name: "" },
      { position: "D", name: "" },
      { position: "M", name: "" },
      { position: "M", name: "" },
      { position: "M", name: "" },
      { position: "M", name: "" },
      { position: "F", name: "" },
      { position: "F", name: "" },
      { position: "F", name: "" },
    ],
  },
  {
    title: "352",
    image: imagesFormations["3-5-2"],
    positions: ["G", "D", "D", "D", "M", "M", "M", "M", "M", "F", "F"],
    selections: [
      { position: "G", name: "" },
      { position: "D", name: "" },
      { position: "D", name: "" },
      { position: "D", name: "" },
      { position: "M", name: "" },
      { position: "M", name: "" },
      { position: "M", name: "" },
      { position: "M", name: "" },
      { position: "M", name: "" },
      { position: "F", name: "" },
      { position: "F", name: "" },
    ],
  },
  {
    title: "41212",
    image: imagesFormations["4-1-2-1-2"],
    positions: ["G", "D", "D", "D", "D", "M", "M", "M", "M", "F", "F"],
    selections: [
      { position: "G", name: "" },
      { position: "D", name: "" },
      { position: "D", name: "" },
      { position: "D", name: "" },
      { position: "D", name: "" },
      { position: "M", name: "" },
      { position: "M", name: "" },
      { position: "M", name: "" },
      { position: "M", name: "" },
      { position: "F", name: "" },
      { position: "F", name: "" },
    ],
  },
  {
    title: "4231",
    image: imagesFormations["4-2-3-1"],
    positions: ["G", "D", "D", "D", "D", "M", "M", "F", "F", "F", "F"],
    selections: [
      { position: "G", name: "" },
      { position: "D", name: "" },
      { position: "D", name: "" },
      { position: "D", name: "" },
      { position: "D", name: "" },
      { position: "M", name: "" },
      { position: "M", name: "" },
      { position: "F", name: "" },
      { position: "F", name: "" },
      { position: "F", name: "" },
      { position: "F", name: "" },
    ],
  },
  {
    title: "433",
    image: imagesFormations["4-3-3"],
    positions: ["G", "D", "D", "D", "D", "M", "M", "M", "F", "F", "F"],
    selections: [
      { position: "G", name: "" },
      { position: "D", name: "" },
      { position: "D", name: "" },
      { position: "D", name: "" },
      { position: "D", name: "" },
      { position: "M", name: "" },
      { position: "M", name: "" },
      { position: "M", name: "" },
      { position: "F", name: "" },
      { position: "F", name: "" },
      { position: "F", name: "" },
    ],
  },
  {
    title: "442",
    image: imagesFormations["4-4-2"],
    positions: ["G", "D", "D", "D", "D", "M", "M", "M", "M", "F", "F"],
    selections: [
      { position: "G", name: "" },
      { position: "D", name: "" },
      { position: "D", name: "" },
      { position: "D", name: "" },
      { position: "D", name: "" },
      { position: "M", name: "" },
      { position: "M", name: "" },
      { position: "M", name: "" },
      { position: "M", name: "" },
      { position: "F", name: "" },
      { position: "F", name: "" },
    ],
  },
  {
    title: "451",
    image: imagesFormations["4-5-1"],
    positions: ["G", "D", "D", "D", "D", "M", "M", "M", "M", "M", "F"],
    selections: [
      { position: "G", name: "" },
      { position: "D", name: "" },
      { position: "D", name: "" },
      { position: "D", name: "" },
      { position: "D", name: "" },
      { position: "M", name: "" },
      { position: "M", name: "" },
      { position: "M", name: "" },
      { position: "M", name: "" },
      { position: "M", name: "" },
      { position: "F", name: "" },
    ],
  },
  {
    title: "532",
    image: imagesFormations["5-3-2"],
    positions: ["G", "D", "D", "D", "D", "D", "M", "M", "M", "F", "F"],
    selections: [
      { position: "G", name: "" },
      { position: "D", name: "" },
      { position: "D", name: "" },
      { position: "D", name: "" },
      { position: "D", name: "" },
      { position: "D", name: "" },
      { position: "M", name: "" },
      { position: "M", name: "" },
      { position: "M", name: "" },
      { position: "F", name: "" },
      { position: "F", name: "" },
    ],
  },
];
