// const goalkeepers = {
//   "Tom Heaton": { name: "Tom Heaton", position: "goalkeeper" },
//   "Jack Butland": { name: "Jack Butland", position: "goalkeeper" },
//   "Aaron Ramsdale": { name: "Aaron Ramsdale", position: "goalkeeper" },
//   "Nick Pope": { name: "Nick Poper", position: "goalkeeper" },
//   "Dean Henderson": { name: "Dean Henderson", position: "goalkeeper" },
//   "Sam Johnstone": { name: "Sam Johnstone", position: "goalkeeper" },
//   "Jordan Pickford": { name: "Jordan Pickford", position: "goalkeeper" },
// };

// const defenders = {
//   "Trent Alexander-Arnold": { name: "Trent Alexander-Arnold", position: "defender" },
//   "Kieran Trippier": { name: "Kieran Trippier", position: "defender" },
//   "Danny Rose": { name: "Danny Rose", position: "defender" },
//   "Michael Keane": { name: "Michael Keane", position: "defender" },
//   "John Stones": { name: "John Stones", position: "defender" },
//   "Joe Gomez": { name: "Joe Gomez", position: "defender" },
//   "Reece James": { name: "Reece James", position: "defender" },
//   "Ben Chilwell": { name: "Ben Chilwell", position: "defender" },
//   "Harry Maguire": { name: "Harry Maguire", position: "defender" },
//   "Luke Shaw": { name: "Luke Shaw", position: "defender" },
//   "Tyrone Mings": { name: "Tyrone Mings", position: "defender" },
//   "Ben White": { name: "Ben White", position: "defender" },
//   "Fikayo Tomori": { name: "Fikayo Tomori", position: "defender" },
//   "Conor Coady": { name: "Conor Coady", position: "defender" },
//   "Kyle Walker": { name: "Kyle Walker", position: "defender" },
// };

// const midfielders = {
//   "Ross Barkley": { name: "Ross Barkley", position: "midfielder" },
//   "James Ward-Prowse": { name: "James Ward-Prowse", position: "midfielder" },
//   "Declan Rice": { name: "Declan Rice", position: "midfielder" },
//   "Jesse Lingard": { name: "Jesse Lingard", position: "midfielder" },
//   "Ben Godfrey": { name: "Ben Godfrey", position: "midfielder" },
//   "Jordan Henderson": { name: "Jordan Henderson", position: "midfielder" },
//   "Eric Dier": { name: "Eric Dier", position: "midfielder" },
//   "Jack Grealish": { name: "Jack Grealish", position: "midfielder" },
//   "Harry Winks": { name: "Harry Winks", position: "midfielder" },
//   "Harvey Barnes": { name: "Harvey Barnes", position: "midfielder" },
//   "Fabian Delph": { name: "Fabian Delph", position: "midfielder" },
//   "Jude Bellingham": { name: "Jude Bellingham", position: "midfielder" },
//   "Mason Mount": { name: "Mason Mount", position: "midfielder" },
//   "Ainsley Maitland-Niles": { name: "Ainsley Maitland-Niles", position: "midfielder" },
//   "Kalvin Phillips": { name: "Kalvin Phillips", position: "midfielder" },
//   "Dele Alli": { name: "Dele Alli", position: "midfielder" },
//   "Callum Hudson-Odoi": { name: "Callum Hudson-Odoi", position: "midfielder" },
//   "James Maddison": { name: "James Maddison", position: "midfielder" },
//   "Alex Oxlade-Chamberlain": { name: "Alex Oxlade-Chamberlain", position: "midfielder" },
// };

// const forwards = {
//   "Raheem Sterling": { name: "Raheem Sterling", position: "forward" },
//   "Bukayo Saka": { name: "Bukayo Saka", position: "forward" },
//   "Phil Foden": { name: "Phil Foden", position: "forward" },
//   "Jadon Sancho": { name: "Jadon Sancho", position: "forward" },
//   "Callum Wilson": { name: "Callum Wilson", position: "forward" },
//   "Marcus Rashford": { name: "Marcus Rashford", position: "forward" },
//   "Dominic Calvert-Lewin": { name: "Dominic Calvert-Lewin", position: "forward" },
//   "Harry Kane": { name: "Harry Kane", position: "forward" },
//   "Tammy Abraham": { name: "Tammy Abraham", position: "forward" },
//   "Ollie Watkins": { name: "Ollie Watkins", position: "forward" },
//   "Patrick Bamford": { name: "Patrick Bamford", position: "forward" },
//   "Danny Ings": { name: "Danny Ings", position: "forward" },
//   "Mason Greenwood": { name: "Mason Greenwood", position: "forward" },
// };

const goalkeepers = [
  { name: "Tom Heaton", position: "G" },
  { name: "Jack Butland", position: "G" },
  { name: "Aaron Ramsdale", position: "G" },
  { name: "Nick Pope", position: "G" },
  { name: "Dean Henderson", position: "G" },
  { name: "Sam Johnstone", position: "G" },
  { name: "Jordan Pickford", position: "G" },
];

const defenders = [
  { name: "Trent Alexander-Arnold", position: "D" },
  { name: "Kieran Trippier", position: "D" },
  { name: "Danny Rose", position: "D" },
  { name: "Michael Keane", position: "D" },
  { name: "John Stones", position: "D" },
  { name: "Joe Gomez", position: "D" },
  { name: "Reece James", position: "D" },
  { name: "Ben Chilwell", position: "D" },
  { name: "Harry Maguire", position: "D" },
  { name: "Luke Shaw", position: "D" },
  { name: "Tyrone Mings", position: "D" },
  { name: "Ben White", position: "D" },
  { name: "Fikayo Tomori", position: "D" },
  { name: "Conor Coady", position: "D" },
  { name: "Kyle Walker", position: "D" },
];

const midfielders = [
  { name: "Ross Barkley", position: "M" },
  { name: "James Ward-Prowse", position: "M" },
  { name: "Declan Rice", position: "M" },
  { name: "Jesse Lingard", position: "M" },
  { name: "Ben Godfrey", position: "M" },
  { name: "Jordan Henderson", position: "M" },
  { name: "Eric Dier", position: "M" },
  { name: "Jack Grealish", position: "M" },
  { name: "Harry Winks", position: "M" },
  { name: "Harvey Barnes", position: "M" },
  { name: "Fabian Delph", position: "M" },
  { name: "Jude Bellingham", position: "M" },
  { name: "Mason Mount", position: "M" },
  { name: "Ainsley Maitland-Niles", position: "M" },
  { name: "Kalvin Phillips", position: "M" },
  { name: "Dele Alli", position: "M" },
  { name: "Callum Hudson-Odoi", position: "M" },
  { name: "James Maddison", position: "M" },
  { name: "Alex Oxlade-Chamberlain", position: "M" },
];

const forwards = [
  { name: "Raheem Sterling", position: "F" },
  { name: "Bukayo Saka", position: "F" },
  { name: "Phil Foden", position: "F" },
  { name: "Jadon Sancho", position: "F" },
  { name: "Callum Wilson", position: "F" },
  { name: "Marcus Rashford", position: "F" },
  { name: "Dominic Calvert-Lewin", position: "F" },
  { name: "Harry Kane", position: "F" },
  { name: "Tammy Abraham", position: "F" },
  { name: "Ollie Watkins", position: "F" },
  { name: "Patrick Bamford", position: "F" },
  { name: "Danny Ings", position: "F" },
  { name: "Mason Greenwood", position: "F" },
];

export const players = {
  goalkeepers,
  defenders,
  midfielders,
  forwards,
};
