export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";

export const ADD_PLAYER = "ADD_PLAYER";
export const ADD_PLAYER_TO_BENCH = "ADD_PLAYER_TO_BENCH";
export const ADD_PLAYER_BACK_INTO_SQUAD_OPTIONS = "ADD_PLAYER_BACK_INTO_SQUAD_OPTIONS";
export const REMOVE_SELECTED_PLAYER_FROM_SQUAD_OPTIONS =
  "REMOVE_SELECTED_PLAYER_FROM_SQUAD_OPTIONS";
export const REMOVE_PLAYER = "REMOVE_PLAYER";
