export const ADD_PLAYER = "ADD_PLAYER";
export const ADD_PLAYER_TO_BENCH = "ADD_PLAYER_TO_BENCH";
export const REMOVE_PLAYER = "REMOVE_PLAYER";
export const UPDATE_FORMATION = "UPDATE_FORMATION";
export const UPDATE_SQUAD_OPTIONS = "UPDATE_SQUAD_OPTIONS";
export const SAVE_SQUAD = "SAVE_SQUAD";
export const LOAD_SQUAD = "LOAD_SQUAD";
export const CLEAR_SQUAD = "CLEAR_SQUAD";
